MODEL_NAME="Qwen/Qwen3-0.6B"
TEST_CASES_FILE="qwen3_0_6b.json"

# Test CPU embedding op only
TEST_OPS_LIST=("TEAttenWithCPEnhanced")
TEST_CASE_IDXS=None
TP_COMM_BUFFER_NAME=None

TP_COMM_OVERLAP=True

TP_SIZE=2
CP_SIZE=1
EP_SIZE=1
ETP_SIZE=1